CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL,
  "status" varchar,
  "created_at" timestamp DEFAULT 'Now()',
  "courses_id" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "courses_id" int,
  "categories_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses_id" int,
  "categories_id" int
);

COMMENT ON COLUMN "users"."status" IS 'Activo o Inactivo';

ALTER TABLE "users" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("categories_id") REFERENCES "categories" ("id");



--CREACION DE USUARIOS

insert into users (
	first_name, 
	last_name, 
	email, 
	"password",
	"age",
	status,
	courses_id 
	)
values (
	'Juan Luis',
	'Orozco',
	'juanluis.o@outlook.com',
	'root',
	'26',
	'Activo',
	'2'
) , (
	'Valeria', 
	'Carrillo', 
	'valeria.cr17@gmail.com', 
	'root',
	'25',
	'Activo',
	'1'
)  , (
	'Miguel',
	'Chavez',
	'mikewazauski16@outlook.com',
	'root',
	'26',
	'Activo',
	'2'
)   , (
	'Guillermo',
	'Ramirez',
	'willyman@live.com',
	'root',
	'24',
	'Activo',
	'1'
)   , (
	'Daniela',
	'Martinez',
	'daniela.mtz21@hotmail.com',
	'root',
	'21',
	'Activo',
	'1'
)

--insert de cursos

insert
	into
	courses (
	title,
	description,
	level,
	teacher
)
values (
  'React with Redux',
  'Learn how to use React applying redux',
  'Medium',
  'Junior Pacheco'
) ,
(
  'PostgreSQL',
  'Learn how to manage database with PostgreSQL',
  'Advance',
  'Sahid Kick'
);

--insert de categorias

insert
	into
	categories (name)
values ('Front End') ,
('Back End');


--insert de tabla pivote

insert
	into
	courses_categories (
	courses_id,
	categories_id 
)
values (
	'1',
	'1'
) ,
( 
	'2',
	'2'
);

--insert de courses_video

insert into courses_video (
	title,
	url,
	courses_id,
	categories_id
) values (
	'Introduccion a React',
	'https://www.courses.com/introduccion-react',
	'1',
	'1'
) , (
	'Que es PostgreSQL',
	'https://www.courses.com/que-es-postgresql',
	'2',
	'2'
)

delete from users where id = 1;
delete from users where id = 2;
delete from users where id = 3;
delete from users where id = 4;
delete from users where id = 5;


